FROM rust:1.76-buster
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y protobuf-compiler libprotobuf-dev
RUN cargo install cargo-watch

EXPOSE 50051
ENV DATABASE_URL=postgres://user:password@db:5432/auth

CMD ["cargo", "watch", "-x", "run"]
