version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
