FROM python:3.8-slim-buster

WORKDIR /app

RUN pip install pytest

COPY ./e2e/auth.py ./auth.py
COPY ./proto ./proto

# Install grpcurl
RUN apt-get update && apt-get install -y curl && \
  curl -sSL https://github.com/fullstorydev/grpcurl/releases/download/v1.8.1/grpcurl_1.8.1_linux_x86_64.tar.gz | tar xz && \
  mv grpcurl /usr/local/bin/grpcurl && \
  chmod +x /usr/local/bin/grpcurl && \
  apt-get remove -y curl && apt-get autoremove -y && apt-get clean

CMD ["pytest", "auth.py"]
